name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint code
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Check TypeScript types
      run: npx tsc --noEmit

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Asciidoctor
      run: npm install @asciidoctor/core
    
    - name: Build project
      run: npm run build
    
    - name: Run integration tests
      run: npm run test:integration
    
    - name: Test CLI usage
      run: |
        echo "const ext = require('./lib/index.js'); module.exports.register = (reg) => ext.default(reg);" > test-ext.js
        npx @asciidoctor/cli -r ./test-ext.js test/example.adoc